### ISSUE TITLE
Seeding when browser is closed?

### ISSUE THREAD

**Issue by newcivics** [beakerbrowser/explore#16]
When I choose to seed files for a site (say, for 7 days), am I only seeding *while beaker browser is open*? Or am I seeding anytime my computer is on? This isn't clear from the docs.

**Comment by RangerMauve** [comment]
Hi, this sort of question would be better posted in https://github.com/beakerbrowser/beaker/issues

However, to answer your question: Beaker is only seeding data while it's running. It doesn't seed things in the background.

If you want an always-on peer, try using [hashbase](https://hashbase.io/) or setting up your own [homebase](https://github.com/beakerbrowser/homebase) server.
