### ISSUE TITLE
Can't see my new dat site experiment listed, is it up and running?

### ISSUE THREAD

**Issue by HyperNorse** [beakerbrowser/explore#17]
That's what my beaker browser shows, wonder if there's a way to attach a simpler url to it too.
I hope the datproject will grow like mad, great innovation!
dat://86c1200a2d9221f4c7452b425b127424ad50357fb36c0ca9ba1f645cb1098b90/DoriTheViking.html

**Comment by pfrazee** [comment]
Hi @HyperNorse, sorry for the delay.

You can read about getting a better URL at https://beakerbrowser.com/docs/guides/use-a-domain-name-with-dat

You can also read about keeping the site online with https://beakerbrowser.com/docs/how-beaker-works/peer-to-peer-websites#keeping-a-peer-to-peer-website-online (the "Keeping a peer-to-peer website online" section).
