### ISSUE TITLE
Text is a little hard to read against images

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/explore#22]
Some of the cards overlay text on top of images. The idea is cool and sometimes I really like it, but it hurts readability and makes the listing hard to scan quickly.

This is especially the case on the p2p web sites:

![screen shot 2018-10-09 at 5 21 54 pm](https://user-images.githubusercontent.com/1270099/46702192-d23e9200-cbe7-11e8-81e8-d8707b77f397.png)

But it's also somewhat true on the less busy items:

![screen shot 2018-10-09 at 5 21 57 pm](https://user-images.githubusercontent.com/1270099/46702217-e4203500-cbe7-11e8-936a-3db1fd156074.png)

Is there a way we can have the imagery without losing some of the readability?

**Comment by taravancil** [comment]
We can play around with other background colors. I think to fit the
aesthetic, black, white and, translucent white are the best options.
