### ISSUE TITLE
Change the filters from combinable toggles to a nav

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/explore#23]
The combinable filter idea is cool but somewhat difficult to use. I think it'd be better if clicking one of the filters just changed to that category.

**Comment by taravancil** [comment]
Can you elaborate about how you think it’s difficult to use?

**Comment by pfrazee** [comment]
I just think it adds UX complexity. Generally speaking it adds clicks, but there are also some weird edge cases (if I click on "websites" and then on "events" nothing happens).
