### ISSUE TITLE
New User Page: dat://edouard.us/

### ISSUE THREAD

**Issue by edouerd** [beakerbrowser/explore#32]
Which category: User Pages
An image (if you have one): ![](https://d2w9rnfcy7mm78.cloudfront.net/495875/large_e71eb3d1e86175faaaed7d46f91c00bf.png?1449237051)
The URL: dat://edouard.us/
A title: Édouard U.
And a description: Édouard's Webpage

**Comment by pfrazee** [comment]
Done!
