### ISSUE TITLE
New user page: dat://e-v-e.hashbase.io/

### ISSUE THREAD

**Issue by eveahe** [beakerbrowser/explore#34]
Hello! 

New to beaker and made a user page as my first step in the exploration. 🌟

**Comment by pfrazee** [comment]
Hi @eveahe! I'll need a picture for your site. Should I use your github avatar?

**Comment by eveahe** [comment]
Hi @pfrazee! I had thought I had uploaded a favicon before, but I think I had done it wrong somehow. Can you see one there now?

**Comment by pfrazee** [comment]
Oh cool, yeah I'll use that. Love the background!

**Comment by pfrazee** [comment]
Done!
