### ISSUE TITLE
USER PAGES

### ISSUE THREAD

**Issue by TrinidadScorpion** [beakerbrowser/explore#40]
Category: Hobbies; Website promotion
Image: use Github image
The URL: dat://2e8f91..e2/
Title: My Interactive Website
Description: Brought my site back from 2006 using all Raspberry PI computers except for one. I also updated the sorrowful looking webpage made with Microsoft Frontpage. 
While looking for a solution to easily convey the newly employed  USERNAME and PASSWORD I found Beaker Browser on the TiddlyWiki.com website. Website promotion has now been my biggest challenge, quite a different world from the days of Netscape Navigator. I am a Power Limited Technician working for a fire alarm company.

**Comment by pfrazee** [comment]
@TrinidadScorpion Hi, can you give me your full dat URL? That's a truncated format that's missing a lot of digits.

**Comment by TrinidadScorpion** [comment]
dat://2e8f91cdc1a1ef22929276170ee79250b10ab49e4536a56004e4d289772127e2/

**Comment by pfrazee** [comment]
Got it! Adding, thanks

**Comment by TrinidadScorpion** [comment]
Thanks Paul!
    I know this probably isn't the right channel to ask a question such as
this, but is there a reason why I can't copy with the mouse in this browser
and then paste somewhere else?

**Comment by pfrazee** [comment]
If you're on windows, there's an open issue for that

**Comment by TrinidadScorpion** [comment]
Yes windows... thank you.
