### ISSUE TITLE
Want To Add My Website

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [beakerbrowser/explore#59]
- Which category

> Personal Website

 - An image (if you have one)

>![EsmailELBoBLogoWithoutFrame](https://user-images.githubusercontent.com/28893833/55091031-04658280-50a8-11e9-83a2-e6ce7ee48efc.png)

 - The URL

>dat://esmailelbob.hashbase.io

 - A title

>Esmail EL BoB

 - And a description

>It's Just Normal/Personal/Open Source Website, Made With HTML, CSS & JS

**Comment by EsmailELBoBDev2** [comment]
ugh forget

**Comment by EsmailELBoBDev2** [comment]
RIP

**Comment by pfrazee** [comment]
Hey I'm sorry, the explore site basically got left behind while we did a major rebuild on Beaker

**Comment by EsmailELBoBDev2** [comment]
Yup i can see that, lol
anyway i opened new issue so when you done with beaker you can add my website.
Thanks
